### PR TITLE
feat(provisioning): extra format options (`mkfs`) added

### LINKED ISSUE #296: Extra mkfs options
**Describe the problem/challenge you have**

I want to use lvm-localpv withing MinIO and some other applications with high number of Inode usage and sometimes I need to inject extra params into `mkfs` command  

**Describe the solution you'd like**

Adding `mkfsOptions` just like `mountOptions`

**Anything else you would like to add:**
I wanted to add this feature as a PR but I don't know where to change the code to add this (I mean connecting parameters struct into formatAndMountSensitive function

(line L358 of pkg/lvm/mount.go)

**Environment:**
- LVM Driver version
- Kubernetes version (use `kubectl version`): 1.28
- Kubernetes installer & version: Kubespray
- Cloud provider or hardware configuration: Self Hosted
- OS (e.g. from `/etc/os-release`): debian bookworm

### PR DESCRIPTION
**Pull request by mhkarimi1383**
## Pull Request template

Please, go through these steps before you submit a PR.

**Why is this PR required? What issue does it fix?**:

adding extra format (`mkfs`) options to newly created Volumes

also switched from deprecated `utils/monut` to `mount-utils` to be able to add this feature and moving from an old package to a maintained one 

**What this PR does?**:

Refactor to new mount utils package and change format and mount function

**Does this PR require any upgrade changes?**:

No, But requires document updates for StorageClasses

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Any additional information for your reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Fixes #296
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [x] Has the change log section been updated?
- [ ] Commit has unit tests
- [x] Commit has integration tests
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track:
- [x] (Optional) If documentation changes are required, which issue on https://github.com/openebs/openebs-docs is used to track them:

### CODE REVIEW

**Comment by dsharma-dc** [comment]
How is the new formatOptions going to be set by user? via storageclass? There is no mkfsOptions unlike mountOptions as provided by storageclass.
Please write  a test as well to show how this is used.

**Comment by tiagolobocastro** [comment]
I think `formatOptions` need to be parsed from storage class at `GetVolAndMountInfo` ?

**Comment by mhkarimi1383** [comment]
Hi

`formatOptions` is added to `MountInfo` just like `mountOptions`

So, It will work if you add it to storageclass

**Comment by mhkarimi1383** [comment]
Also there is no test for the mounter itself

**Comment by dsharma-dc** [comment]
> I think `formatOptions` need to be parsed from storage class at `GetVolAndMountInfo` ?

`GetVolAndMountInfo`  is parsing and **building** mountinfo from csi node publish request, but I don't see anything for format options in csi request. So I wonder how that's going to work. The storageclass parsing is being done in `NewVolumeParams` that's part of controller plugin.
cc: @abhilashshetty04

**Comment by dsharma-dc** [comment]
> Also there is no test for the mounter itself

You can run this manually and document here the steps to set formatOptions.

**Comment by mhkarimi1383** [comment]
> > I think `formatOptions` need to be parsed from storage class at `GetVolAndMountInfo` ?
> 
> `GetVolAndMountInfo`  is parsing and **building** mountinfo from csi node publish request, but I don't see anything for format options in csi request. So I wonder how that's going to work. The storageclass parsing is being done in `NewVolumeParams` that's part of controller plugin.
> cc: @abhilashshetty04 

It's my first time that I'm contributing to this project so I just looked for where mountOptions is handled to handle formatOptions too

**Comment by mhkarimi1383** [comment]
Hello again

I'm using NixOS, and I can't run `make`, waiting on https://github.com/openebs/lvm-localpv/pull/351

**Comment by mhkarimi1383** [comment]
> I think `formatOptions` need to be parsed from storage class at `GetVolAndMountInfo` ?

I checked out more and I saw that we have to put this on where we are mounting volume for the first time, So there is no need to add this into `GetVolAndMountInfo`, we have to handle that just like `mountOptions`

**Comment by mhkarimi1383** [comment]
Not able to test due to https://github.com/openebs/lvm-localpv/issues/353 and https://github.com/openebs/lvm-localpv/pull/352

File: go.mod [hunk 1]
```diff
@@ -1,6 +1,8 @@
 module github.com/openebs/lvm-localpv
 
-go 1.19
+go 1.22.0
```
Comment (dsharma-dc) [inline go.mod]: This is causing github actions to fail. Let's not update this until we uniformly upgrade to golang 1.22 throughout.

**Comment by dsharma-dc** [comment]
@mhkarimi1383 
Also, please refer to the change https://github.com/openebs/zfs-localpv/pull/542/files . Something similar is likely required here also for these formatOptions to be usable.
cc: @abhilashshetty04 @Abhinandan-Purkait

File: go.mod (hunk 1 above)
Comment (mhkarimi1383) [reply go.mod]: I will revert that

My go version was the cause of this, That's why I have contributed for Nix Shell :)

**Comment by mhkarimi1383** [comment]
@dsharma-dc 

golint-ci returns error

```
pkg/driver/controller.go:338:6: declared and not used: vol (typecheck)
	var vol *lvmapi.LVMVolume
	   ^
pkg/lvm/mount.go:31:2: could not import k8s.io/mount-utils (-: cannot compile Go 1.22 code) (typecheck)
	"k8s.io/mount-utils"
	^
pkg/lvm/mount.go:73:14: undefined: mount (typecheck)
	mounter := &mount.SafeFormatAndMount{Interface: mount.New(""), Exec: utilexec.New()}
	           ^
pkg/lvm/mount.go:97:14: undefined: mount (typecheck)
	mounter := &mount.SafeFormatAndMount{Interface: mount.New(""), Exec: utilexec.New()}
	           ^
pkg/lvm/mount.go:99:19: undefined: mount (typecheck)
	dev, ref, err := mount.GetDeviceNameFromMount(mounter, targetPath)
	                ^
make: *** [Makefile:263: golint] Error 1
```

I think to update to `k8s.io/mount-utils` we have to update go version

**Comment by dsharma-dc** [comment]
> @dsharma-dc
> 
> golint-ci returns error
> 
> ```
> pkg/driver/controller.go:338:6: declared and not used: vol (typecheck)
> 	var vol *lvmapi.LVMVolume
> 	   ^
> pkg/lvm/mount.go:31:2: could not import k8s.io/mount-utils (-: cannot compile Go 1.22 code) (typecheck)
> 	"k8s.io/mount-utils"
> 	^
> pkg/lvm/mount.go:73:14: undefined: mount (typecheck)
> 	mounter := &mount.SafeFormatAndMount{Interface: mount.New(""), Exec: utilexec.New()}
> 	           ^
> pkg/lvm/mount.go:97:14: undefined: mount (typecheck)
> 	mounter := &mount.SafeFormatAndMount{Interface: mount.New(""), Exec: utilexec.New()}
> 	           ^
> pkg/lvm/mount.go:99:19: undefined: mount (typecheck)
> 	dev, ref, err := mount.GetDeviceNameFromMount(mounter, targetPath)
> 	                ^
> make: *** [Makefile:263: golint] Error 1
> ```
> 
> I think to update to `k8s.io/mount-utils` we have to update go version

Would you like to do that as part of this PR? or instead try using a `mount-utils` that might work with go 1.19.

**Comment by mhkarimi1383** [comment]
I can do both, whatever is Ok :)

**Comment by dsharma-dc** [comment]
> I can do both, whatever is Ok :)

Thanks, I'd say then try using a compatible `mount-utils` version(I hope no other issues pop up), and Go upgrade can be taken up as a new PR.

**Comment by mhkarimi1383** [comment]
@dsharma-dc 

Ok, I will revert my changes to go.mod, etc. And will change the package again

**Comment by mhkarimi1383** [comment]
I have fixed package versions and switched to a correct version of mount utils

And I was able to build project successfully and tests passed

**Comment by mhkarimi1383** [comment]
Also why in `Makefile` we are using sudo to build images?
It will break systems with podman

**Comment by mhkarimi1383** [comment]
Also getting

`/usr/local/bin/lvm-driver`: No such file or directory

after building and running built image

Both with sudo and without sudo while building...

**Comment by mhkarimi1383** [comment]
I think this is due to some shared libs
We could make go build to do everything statistically

As I understood that's because of my Operating System (NixOS), since it has different type of packaging/paths

**Comment by dsharma-dc** [comment]
> Also why in `Makefile` we are using sudo to build images? It will break systems with podman

Perhaps because Podman is pretty new compared to Docker, when this Makefile was written. We may want to change that at some point.

**Comment by dsharma-dc** [comment]
> @mhkarimi1383 Also, please refer to the change https://github.com/openebs/zfs-localpv/pull/542/files . Something similar is likely required here also for these formatOptions to be usable. cc: @abhilashshetty04 @Abhinandan-Purkait

@mhkarimi1383 Did you see this comment yet?

**Comment by mhkarimi1383** [comment]
> > @mhkarimi1383 Also, please refer to the change https://github.com/openebs/zfs-localpv/pull/542/files . Something similar is likely required here also for these formatOptions to be usable. cc: @abhilashshetty04 @Abhinandan-Purkait
> 
> @mhkarimi1383 Did you see this comment yet?

Yes,

But since I'm a bit new to this project I need to run the project locally on my minikube setup
Due to shared libs problem I can't test it locally

**Comment by mhkarimi1383** [comment]
It is OK to remove `sudo` and make builds static?
Or I have to do it in another PR?

**Comment by tiagolobocastro** [comment]
> It is OK to remove `sudo` and make builds static? Or I have to do it in another PR?

Why is static builds required? Isn't having all required inputs in the nix-shell enough?

**Comment by mhkarimi1383** [comment]
> > It is OK to remove `sudo` and make builds static? Or I have to do it in another PR?
> 
> Why is static builds required? Isn't having all required inputs in the nix-shell enough?


Paths are different there and I think because of that 
I'm getting 

/usr/local/bin/lvm-driver: No such file or directory

While running the built image

I think making builds static will make the binary file work everywhere :)

Just guessing :)
I think I have to give static build a try

**Comment by mhkarimi1383** [comment]
After trying to do static link some libs are missing again, getting

```
ldd /usr/local/bin/lvm-driver
	/nix/store/9v5d40jyvmwgnq1nj8f19ji2rcc5dksd-glibc-2.37-45/lib/ld-linux-x86-64.so.2 (0x7f2f6b592000)
	libpthread.so.0 => /nix/store/9v5d40jyvmwgnq1nj8f19ji2rcc5dksd-glibc-2.37-45/lib/ld-linux-x86-64.so.2 (0x7f2f6b592000)
	libc.so.6 => /nix/store/9v5d40jyvmwgnq1nj8f19ji2rcc5dksd-glibc-2.37-45/lib/ld-linux-x86-64.so.2 (0x7f2f6b592000)
Error relocating /usr/local/bin/lvm-driver: __vfprintf_chk: symbol not found
Error relocating /usr/local/bin/lvm-driver: __fprintf_chk: symbol not found
```

**Comment by mhkarimi1383** [comment]
I can't test this project when using NixOS, Using docker for build is a good option too

**Comment by mhkarimi1383** [comment]
For me problem solved by these changes

If it's OK, I will create a new PR to apply them (I don't know if you are Ok with using musl)


```patch
diff --git a/Makefile b/Makefile
index dda7432..27501c3 100644
--- a/Makefile
+++ b/Makefile
@@ -222,7 +222,7 @@ lvm-driver-image: lvm-driver
    @echo "+ Generating ${CSI_DRIVER} image"
    @echo "--------------------------------"
    @cp bin/${CSI_DRIVER}/${CSI_DRIVER} buildscripts/${CSI_DRIVER}/
-   cd buildscripts/${CSI_DRIVER} && sudo docker build -t ${IMAGE_ORG}/${CSI_DRIVER}:${IMAGE_TAG} ${DBUILD_ARGS} . && sudo docker tag ${IMAGE_ORG}/${CSI_DRIVER}:${IMAGE_TAG} quay.io/${IMAGE_ORG}/${CSI_DRIVER}:${IMAGE_TAG}
+   cd buildscripts/${CSI_DRIVER} && docker build -t ${IMAGE_ORG}/${CSI_DRIVER}:${IMAGE_TAG} ${DBUILD_ARGS} . && docker tag ${IMAGE_ORG}/${CSI_DRIVER}:${IMAGE_TAG} quay.io/${IMAGE_ORG}/${CSI_DRIVER}:${IMAGE_TAG}
    @rm buildscripts/${CSI_DRIVER}/${CSI_DRIVER}
 
 .PHONY: ansible-runner-image
@@ -230,7 +230,7 @@ ansible-runner-image:
    @echo "------------------"
    @echo "--> Build ansible-runner image for lvm-localpv e2e-tests" 
    @echo "------------------"
-   sudo docker build . -f e2e-tests/Dockerfile -t ${IMAGE_ORG}/lvm-localpv-e2e:ci
+   docker build . -f e2e-tests/Dockerfile -t ${IMAGE_ORG}/lvm-localpv-e2e:ci
 
 .PHONY: ci
 ci:
diff --git a/buildscripts/build.sh b/buildscripts/build.sh
index a6e7be5..9b3374e 100755
--- a/buildscripts/build.sh
+++ b/buildscripts/build.sh
@@ -100,8 +100,9 @@ env GOOS=$GOOS GOARCH=$GOARCH go build -ldflags \
     "-X github.com/openebs/lvm-localpv/pkg/version.GitCommit=${GIT_COMMIT} \
     -X main.CtlName='${CTLNAME}' \
     -X github.com/openebs/lvm-localpv/pkg/version.Version=${VERSION} \
-    -X github.com/openebs/lvm-localpv/pkg/version.VersionMeta=${VERSION_META}"\
-    -o $output_name\
+    -X github.com/openebs/lvm-localpv/pkg/version.VersionMeta=${VERSION_META} \
+    -linkmode external -w -extldflags '-static'"\
+    -a -o $output_name\
     ./cmd
 
 echo ""
diff --git a/shell.nix b/shell.nix
index d070f65..58acd8d 100644
--- a/shell.nix
+++ b/shell.nix
@@ -4,7 +4,9 @@ let
 in
 pkgs.mkShell {
   name = "scripts-shell";
+
   buildInputs = with pkgs; [
+    nix-ld                # Enable nix-ld linker
     chart-testing
     ginkgo
     git
@@ -16,7 +18,14 @@ pkgs.mkShell {
     minikube
     semver-tool
     yq-go
+    musl                  # Musl for static linking
+    gcc
+    binutils
+    gdb
+    coreutils
+    stdenv.cc.cc
   ];
+
   shellHook = ''
     export HOME=${builtins.getEnv "HOME"}
     export GOPATH=$(pwd)/nix/.go
```

**Comment by dsharma-dc** [comment]
I would say if above changes to build let you test things locally, you can go ahead and make only functional changes in this PR and let the build remain as is for now.
cc: @tiagolobocastro , @abhilashshetty04 , @abhilashshetty04

**Comment by mhkarimi1383** [comment]
> I would say if above changes to build let you test things locally, you can go ahead and make only functional changes in this PR and let the build remain as is for now.
> cc: @tiagolobocastro , @abhilashshetty04 , @abhilashshetty04 

I'm having the same idea too, But making project testable in any system regardless of OS is good thing to have
So I can submit changes in another PR later on...

**Comment by mhkarimi1383** [comment]
> I would say if above changes to build let you test things locally, you can go ahead and make only functional changes in this PR and let the build remain as is for now.
> cc: @tiagolobocastro , @abhilashshetty04 , @abhilashshetty04 

I'm having the same idea too, But making project testable in any system regardless of OS is good thing to have
So I can submit changes in another PR later on...

**Comment by mhkarimi1383** [comment]
JSON Array fields are not working in StorageClass Parameters, See https://github.com/openebs/lvm-localpv/issues/359

**Comment by mhkarimi1383** [comment]
Hello again,
Now I Understood that how volume creation works, after reading the code more deeply :)

and I have added new parameter to the correct locations (I think)
But When I create a storageclass and volume with new option The options does not appear in LVMVolume object

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvmpv
parameters:
  storage: "lvm"
  volgroup: "lvmvg"
  formatoptions: '-N "4000000000"'
provisioner: local.csi.openebs.io
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: csi-lvmpv
spec:
  storageClassName: openebs-lvmpv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: fio
spec:
  restartPolicy: Never
  containers:
  - name: perfrunner
    image: openebs/tests-fio
    command: ["/bin/bash"]
    args: ["-c", "tail -f /dev/null"]
    volumeMounts:
       - mountPath: /datadir
         name: fio-vol
    tty: true
  volumes:
  - name: fio-vol
    persistentVolumeClaim:
      claimName: csi-lvmpv
```


Trying to figure out the problem

**Comment by tiagolobocastro** [comment]
>   formatoptions: '-N "4000000000"'
> 
> Trying to figure out the problem

Should be `formatOptions`

**Comment by mhkarimi1383** [comment]
> > formatoptions: '-N "4000000000"'
> > Trying to figure out the problem
> 
> Should be `formatOptions`

Parameters are converting to lowercase (in `helpers.GetCaseInsensitiveMap`), So it should be OK, I will test it out.

UPDATE: tested and not worked :/

**Comment by tiagolobocastro** [comment]
Could this be because the volume crd need a version bump?

**Comment by mhkarimi1383** [comment]
> Could this be because the volume crd need a version bump?

I have checked that new field is applied in the CRD

**Comment by dsharma-dc** [comment]
@mhkarimi1383 Are you still on with testing your changes? Please let us know how we should proceed with this.

**Comment by mhkarimi1383** [comment]
> @mhkarimi1383 Are you still on with testing your changes? Please let us know how we should proceed with this.

I'm in the phase of debugging this, getting no error and options are not getting reflected into the created LVM Volume object in K8s

Trying to debug that deeply to see what's the problem

**Comment by mhkarimi1383** [comment]
Problem Solved, In logs I found that spec.formatOptions is unknown, I found that `make manifast` and generate_manifasts.sh script is not generating CRDs that are in helm chart, Fixed by manually replacing CRDs

What I have to do to regenerate helm chart CRDs?


I'm so happy that I got this error :)

```
MountVolume.SetUp failed for volume "pvc-19e34f96-7d76-4ae6-a524-389739d750e4" : rpc error: code = Internal desc = failed to format and mount the volume error: format of disk "/dev/lvmvg/pvc-19e34f96-7d76-4ae6-a524-389739d750e4" failed: type:("ext4") target:("/var/lib/kubelet/pods/69700b5c-4607-4329-8622-3f5c0096e225/volumes/kubernetes.io~csi/pvc-19e34f96-7d76-4ae6-a524-389739d750e4/mount") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.47.0 (5-Feb-2023)
mkfs.ext4: inode_size (256) * inodes_count (4000000000) too big for a
  filesystem with 1048576 blocks, specify higher inode_ratio (-i)
  or lower inode count (-N).

)
```

**Comment by mhkarimi1383** [comment]
Also a document update is required :)

**Comment by dsharma-dc** [comment]
Sounds good. Could you also add some unit tests for this. e.g. one positive(set format option and validate setting) and one negative case(set formatoption and expect failure like you did for inodecount above)

> What I have to do to regenerate helm chart CRDs?

@abhilashshetty04

**Comment by mhkarimi1383** [comment]
> Sounds good. Could you also add some unit tests for this. e.g. one positive(set format option and validate setting) and one negative case(set formatoption and expect failure like you did for inodecount above)
> 

I should only test that if that everything successfully works, or I have to verify that options are propagated? Since checking this part is a bit complex

**Comment by mhkarimi1383** [comment]
I have to add some new tests to volumeCreationTest

**Comment by dsharma-dc** [comment]
If checking the set formatOption values turns out to be tricky you may try verifying functionally. For example - set a very low limit with `-N` and create more files that runs over this limit.

**Comment by mhkarimi1383** [comment]
> If checking the set formatOption values turns out to be tricky you may try verifying functionally. For example - set a very low limit with `-N` and create more files that runs over this limit.

Will try to do that :)
I'm not so good at writing tests...

File: deploy/lvm-operator.yaml [hunk 2]
```diff
@@ -95,6 +95,12 @@ spec:
                 description: Capacity of the volume
                 minLength: 1
                 type: string
+              formatOptions:
+                description: FormatOptions specifies additional options while formatting
```
Comment (abhilashshetty04) [inline deploy/lvm-operator.yaml]: Is this upgrade safe? I mean if you upgrade CRD when there are old version of LVMVolume cr present on cluster?

Comment (mhkarimi1383) [reply deploy/lvm-operator.yaml]: It's just a new optional field, nothing will happen...

Comment (abhilashshetty04) [reply deploy/lvm-operator.yaml]: Right. I'd say lets still test it just to be sure.

Comment (mhkarimi1383) [reply deploy/lvm-operator.yaml]: Okay :), will test it out after writing the unit tests

Comment (mhkarimi1383) [reply deploy/lvm-operator.yaml]: It was fine in my tests...

**Comment by mhkarimi1383** [comment]
Test is failing I looks like due to
```
W0319 20:37:42.950952       1 warnings.go:70] unknown field "spec.formatOptions"
```

See: https://github.com/openebs/lvm-localpv/actions/runs/13956138799/job/39067688864?pr=335#step:9:565

Since Helm CRDs are not updated yet


My Locally emulated test for provided options:

```shell
λ  truncate -s 5G /tmp/disk.img
λ  sudo losetup -f /tmp/disk.img --show
/dev/loop1
λ  tune2fs -l /dev/loop1 | grep "Inode count"
Inode count:              1000320

λ  sudo mkfs.ext4 /dev/loop1 -b 4096 -N 5000000
mke2fs 1.47.2 (1-Jan-2025)
/dev/loop1 contains a ext4 file system
	created on Wed Mar 19 23:39:49 2025
Proceed anyway? (y,N) y
Discarding device blocks: done                            
Creating filesystem with 1310720 4k blocks and 5001264 inodes
Filesystem UUID: c0e8f2a6-0bac-442e-966a-cab10de1a0f4
Superblock backups stored on blocks: 
	8608, 25824, 43040, 60256, 77472, 215200, 232416, 421792, 697248, 
	1076000

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done
```

**Comment by mhkarimi1383** [comment]
Also I think a cluster dump is needed after tests...

Sometimes tests pods logs are also needed

**Comment by abhilashshetty04** [comment]
@mhkarimi1383 , We need not set formatOptions on LVMVolume CR. We dont want this info on Node plugin ops anyway right?

We do format and Mount during NodePublishVolume, So you can use volume_context (in NodePublishVolumeRequest) to get the formatOptions set on sc.

volume_context is returned in CreateVolumeResponse.

https://github.com/openebs/lvm-localpv/blob/develop/pkg/driver/controller.go#L364

**Comment by mhkarimi1383** [comment]
@abhilashshetty04, I think it's good to have this in CR because we can change this parameter by recreating StorageClass, with that we are able to access this parameter later on

**Comment by abhilashshetty04** [comment]
@mhkarimi1383 ,What do you mean by update lvmvolume cr field by recreating the sc..

Will we need this params apart from format and mount workflow?

**Comment by mhkarimi1383** [comment]
> @mhkarimi1383 ,What do you mean by update lvmvolume cr field by recreating the sc..
> 
> Will we need this params apart from format and mount workflow?

I mean we could have access to see parameters later on
And when we recreate sc and change the parameters we can lose them, it's good to have them to be able to see how the volume is created later on.

It's not needed in the flow itself

**Comment by abhilashshetty04** [comment]
> I mean we could have access to see parameters later on
And when we recreate sc and change the parameters we can lose them, it's good to have them to be able to see how the volume is created later on.

> It's not needed in the flow itself

There are few parameters on sc that doesn't go into CR as its not needed for lvm specific operations. For example, allowedTopologies. I feel since this parameter is not needed for lvm specific operations it shouldnt be there on CR. It might get confusing to understand the decision behind if we keep it.

We recently added this in mayastor also using volume_context. 

Please refer:
https://github.com/openebs/mayastor-control-plane/pull/954

cc: @dsharma-dc  @tiagolobocastro @Abhinandan-Purkait

**Comment by mhkarimi1383** [comment]
@abhilashshetty04 

Ok I will try to change the flow to not change CR

**Comment by tiagolobocastro** [comment]
I think the `formatOptions` will not be lost as long as the parameters are returned in the volume context returned on `createVolume`.
Then you can check them in the `PersistentVolume` at `.spec.csi.volumeAttributes`.

**Comment by mhkarimi1383** [comment]
@tiagolobocastro @abhilashshetty04

I have refactored formatOptions to use volume context, It should be OK now

**Comment by mhkarimi1383** [comment]
Tests are failing due to pve already exists, and my newly added test did not run

**Comment by tiagolobocastro** [comment]
Seems to be failing with some argument formatting error?

```text
E0420 10:03:54.534370       1 grpc.go:79] GRPC error: rpc error: code = Internal desc = failed to format and mount the volume error: format of disk "/dev/lvmvg/pvc-bb191605-f11e-4e6d-94b1-a6ee8a2f80cf" failed: type:("ext4") target:("/var/lib/kubelet/pods/7cbb193c-b511-4ffb-b38f-1018d4f1c7da/volumes/kubernetes.io~csi/pvc-bb191605-f11e-4e6d-94b1-a6ee8a2f80cf/mount") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.47.0 (5-Feb-2023)
mkfs.ext4: invalid blocks '-F' on device ''
```

**Comment by mhkarimi1383** [comment]
> Seems to be failing with some argument formatting error?
> 
> ```text
> E0420 10:03:54.534370       1 grpc.go:79] GRPC error: rpc error: code = Internal desc = failed to format and mount the volume error: format of disk "/dev/lvmvg/pvc-bb191605-f11e-4e6d-94b1-a6ee8a2f80cf" failed: type:("ext4") target:("/var/lib/kubelet/pods/7cbb193c-b511-4ffb-b38f-1018d4f1c7da/volumes/kubernetes.io~csi/pvc-bb191605-f11e-4e6d-94b1-a6ee8a2f80cf/mount") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.47.0 (5-Feb-2023)
> mkfs.ext4: invalid blocks '-F' on device ''
> ```

But I don't see the start of my tests in the logs, Also I have not set any -F option

**Comment by abhilashshetty04** [comment]
> But I don't see the start of my tests in the logs, Also I have not set any -F option

@mhkarimi1383 , Let me have a look at it.

**Comment by abhilashshetty04** [comment]
@mhkarimi1383 I did try locally also. I got stuck myself because of PVC not getting Bound. FInally figured out that it was due to GO int limitation which was causing parsing issue. All test in develop passes after this fix.

https://github.com/openebs/lvm-localpv/pull/387

For failure in current PR. It seems to be failing during the mount. Pod is not going into Running state. This PR involves changes to mount logic also. Can you please test it manually also.

> E0420 10:03:54.534370       1 grpc.go:79] GRPC error: rpc error: code = Internal desc = failed to format and mount the volume error: format of disk "/dev/lvmvg/pvc-bb191605-f11e-4e6d-94b1-a6ee8a2f80cf" failed: type:("ext4") target:("/var/lib/kubelet/pods/7cbb193c-b511-4ffb-b38f-1018d4f1c7da/volumes/kubernetes.io~csi/pvc-bb191605-f11e-4e6d-94b1-a6ee8a2f80cf/mount") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.47.0 (5-Feb-2023)
mkfs.ext4: invalid blocks '-F' on device ''

**Comment by mhkarimi1383** [comment]
@abhilashshetty04 

Will apply https://patch-diff.githubusercontent.com/raw/openebs/lvm-localpv/pull/387.patch locally and will do build and test

**Comment by abhilashshetty04** [comment]
> @abhilashshetty04
> 
> Will apply https://patch-diff.githubusercontent.com/raw/openebs/lvm-localpv/pull/387.patch locally and will do build and test

This patch is unrelated to the errors that we have on this PR. You might have to look into mount code changes that was done.

**Comment by mhkarimi1383** [comment]
Found the problem with this,

```go
package main

import (
	"fmt"
	"strings"
)

func main() {
	splitted := strings.Split("", " ")
	fmt.Println(len(splitted))
	fmt.Println(splitted[0])
}
```

will print

```
1

```


> Notice empty line

This will cause the format command to be something like

```shell
mkfs.ext4 "" -F -m0 ./a.img
```

**Comment by mhkarimi1383** [comment]
Now every thing is correct, I just have to work on the test case


```
I0424 20:51:44.835644       1 grpc.go:72] GRPC call: /csi.v1.Node/NodePublishVolume requests {"target_path":"/var/lib/kubelet/pods/e081a5a3-346c-45fd-bebd-770fdb3f78de/volumes/kubernetes.io~csi/pvc-eb7f5060-9c8e-46ff-88bd-a7fd04aaf571/mount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"csi.storage.k8s.io/ephemeral":"false","csi.storage.k8s.io/pod.name":"format-options-verifier-7d5d49cf75-nw4lp","csi.storage.k8s.io/pod.namespace":"openebs","csi.storage.k8s.io/pod.uid":"e081a5a3-346c-45fd-bebd-770fdb3f78de","csi.storage.k8s.io/serviceAccount.name":"default","openebs.io/cas-type":"localpv-lvm","openebs.io/format-options":"-b 4096 -N 5000000","openebs.io/volgroup":"lvmvg","storage.kubernetes.io/csiProvisionerIdentity":"1745527750375-7479-local.csi.openebs.io"},"volume_id":"pvc-eb7f5060-9c8e-46ff-88bd-a7fd04aaf571"}
I0424 20:51:44.844322       1 mount_linux.go:516] Disk "/dev/lvmvg/pvc-eb7f5060-9c8e-46ff-88bd-a7fd04aaf571" appears to be unformatted, attempting to format as type: "ext4" with options: [-b 4096 -N 5000000 -F -m0 /dev/lvmvg/pvc-eb7f5060-9c8e-46ff-88bd-a7fd04aaf571]
```

**Comment by mhkarimi1383** [comment]
Also I found test problem

Containers are not able to do `tune2fs` since they only get a mapped device I think

**Comment by mhkarimi1383** [comment]
My test case is OK now, but the only problem is that

bash -c "[ \"$(df -i '/mnt/datadir' | tail -n 1 | awk '{print $2}')\" -ge \"$MIN_INODES\" ]
is working in a normal shell

but 

[`bash`, `-c`, `[ "$(df -i '/mnt/datadir' | tail -n 1 | awk '{print $2}')" -ge "$MIN_INODES" ]` ]

Is failing

Trying to find the reason and fix that

**Comment by mhkarimi1383** [comment]
Found the issue, We are using deployments to test things but here I only need the container to success fully exit

**Comment by mhkarimi1383** [comment]
@abhilashshetty04, @tiagolobocastro

I have done with tests ;)

**Comment by mhkarimi1383** [comment]
Also it's good to make tests to run in parallel in CI I think

**Comment by abhilashshetty04** [comment]
> Also it's good to make tests to run in parallel in CI I think

Lets do a separate PR for that. We dont have bors or similar utility inplace for that right now in localpv repo.

**Comment by mhkarimi1383** [comment]
> > Also it's good to make tests to run in parallel in CI I think
> 
> Lets do a separate PR for that. We dont have bors or similar utility inplace for that right now in localpv repo.


Yeah we should check if we don't have any naming conflicts, etc in resources that are creating in K8s but ginkgo has support for parallel tests

File: changelogs/unreleased/335-mhkarimi1383 [hunk 3]
```diff
@@ -0,0 +1,3 @@
+extra format options (mkfs) added
+
+used to add extra options to mkfs while creating new volumes
```
Comment (abhilashshetty04) [inline changelogs/unreleased/335-mhkarimi1383]:
```suggestion
used to add extra options to mkfs while formatting volumes with filesystem
```

**Comment by abhilashshetty04** [comment]
> > > Also it's good to make tests to run in parallel in CI I think
> > 
> > 
> > Lets do a separate PR for that. We dont have bors or similar utility inplace for that right now in localpv repo.
> 
> Yeah we should check if we don't have any naming conflicts, etc in resources that are creating in K8s but ginkgo has support for parallel tests

Got it. We definately check it out.

**Review by abhilashshetty04 — APPROVED** [review]
Thanks, Please squash commits before merging @mhkarimi1383

**Comment by mhkarimi1383** [comment]
> Thanks, Please squash commits before merging @mhkarimi1383 

I will

File: tests/utils.go [hunk 4]
```diff
@@ -560,6 +596,77 @@ func createAndDeployBlockAppPod() {
...
+									Name:  "EXPECTED_INODES",
+									Value: "5001264",
+								},
+							},
+						).
+						WithCommandNew(
+							[]string{
+								"bash",
+								"-c",
+								`export DEVICE=$(df --output=source '/mnt/datadir' | tail -n 1); export ACTUAL_INODES=$(tune2fs -l "$DEVICE" | grep "Inode count" | awk '{print $3}'); [ "$ACTUAL_INODES" -eq "$EXPECTED_INODES" ] && echo "Inode count is correct: $ACTUAL_INODES" && exit 0 || echo "Inode count mismatch: expected $EXPECTED_INODES, but got $ACTUAL_INODES" && exit 1`,
```
Comment (dsharma-dc) [inline tests/utils.go]: Have you also tested the feature with non-ext filesystems e.g. xfs? I'm assuming the test creates ext4 because tune2fs will only work for ext2/3/4 filesystems.

Comment (mhkarimi1383) [reply tests/utils.go]: I have changed the command to use df -i since tune2fs is not working in lvm volume devices that are available in pods

Also it is a bit tricky to test format options, So I have managed to change inode count and verify that, because of that, the test only covers ext4 filesystem

**Review by dsharma-dc — APPROVED** [review]

**Comment by mhkarimi1383** [comment]
@abhilashshetty04 
Squshed.

I had to recreate branch and apply diff of the PR, Because of some merge commits, etc.

**Comment by dsharma-dc** [comment]
anything pending before merge here, @mhkarimi1383 @abhilashshetty04 ?

**Comment by mhkarimi1383** [comment]
> anything pending before merge here, @mhkarimi1383 @abhilashshetty04 ?

I'm Done with this PR, LGTM

**Comment by mhkarimi1383** [comment]
I can Also add a Test case for xfs using it's block size option, But IDK if xfs_info is available to the pods or not

**Comment by abhilashshetty04** [comment]
Can you please rebase @mhkarimi1383

**Comment by mhkarimi1383** [comment]
@abhilashshetty04 Rebased

**Comment by dsharma-dc** [comment]
@mhkarimi1383 Could you please update the documentation here: https://github.com/openebs/lvm-localpv/blob/develop/docs/storageclasses.md , based on your changes?

**Comment by mhkarimi1383** [comment]
@dsharma-dc I will

**Comment by mhkarimi1383** [comment]
@dsharma-dc 

Covered in
https://github.com/openebs/lvm-localpv/pull/396
